export default {
  id: 'id',
  dados: 'data',
  ultimaAtualizacao: 'lastUpdate',
  nome: 'name',
  siglaPartido: 'party',
  uriPartido: 'partyUrl',
  siglaUf: 'state',
  idLegislatura: 'legislatureId',
  urlFoto: 'photo',
  nomeCivil: 'fullName',
  uri: 'oficialPage',
  cpf: 'oficialDocument',
  sexo: 'sex',
  dataNascimento: 'dateOfBirth',
  dataFalecimento: 'dateOfDeath',
  ufNascimento: 'birthState',
  municipioNascimento: 'birthCity',
  escolaridade: 'scholarship',
  email: 'email',
  sala: 'room',
  gabinete: 'cabinet',
  predio: 'building',
  telefone: 'phone',
  andar: 'floor',
  data: 'date'
}
